version: '3.3'
services:
  mysql:
    image: mysql:5.6
    ports:
      - "13306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      TZ: Japan
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: password
